import { ColorAliasesObject, NonColorCSSVariables } from './generateCSSVars';
import {
    colorCritical400,
    colorCritical50,
    colorCritical500,
    colorInfo400,
    colorInfo50,
    colorInfo600,
    colorInfo700,
    colorPrimary500,
    colorPrimary700,
    colorPrimary900,
    colorSecondary50,
    colorSuccess300,
    colorSuccess50,
    colorSuccess700,
    colorSuccess900,
    colorSurface100,
    colorSurface200,
    colorSurface300,
    colorSurface50,
    colorSurface500,
    colorSurface900,
    colorTertiary50,
    colorWarning300,
    colorWarning50,
    colorWarning500,
    colorWarning600,
    colorWarning800,
} from '../tailwind/cssVars';
import { colorStepArrayToObject, generateNormalColorSteps, generateSurfaceColorSteps } from '../utils/color';
import { wrapOpacity, wrapVar } from '../utils/wrapVar';

export const coreColors = {
    amber: colorStepArrayToObject(generateNormalColorSteps('#F59E0B')),
    blue: colorStepArrayToObject(generateNormalColorSteps('#3B82F6')),
    gray: colorStepArrayToObject(generateNormalColorSteps('#6B7280')),
    green: colorStepArrayToObject(generateNormalColorSteps('#22C55E')),
    neutral: colorStepArrayToObject(generateSurfaceColorSteps('#6B7280', true)),
    red: colorStepArrayToObject(generateNormalColorSteps('#EF4444')),
    stone: colorStepArrayToObject(generateNormalColorSteps('#78716C')),
    zinc: colorStepArrayToObject(generateNormalColorSteps('#71717A')),
};

export const colorAliases = {
    critical: coreColors.red,
    info: coreColors.blue,
    primary: coreColors.gray,
    secondary: coreColors.zinc,
    success: coreColors.green,
    surface: coreColors.neutral,
    tertiary: coreColors.stone,
    warning: coreColors.amber,
} satisfies ColorAliasesObject;

export const nonColorVariables = {
    '--box-shadow-01': `0px 4px 4px ${wrapOpacity(wrapVar(colorSurface200), 50)}`,
    '--box-shadow-02': `0px 1px 4px ${wrapOpacity(wrapVar(colorSurface300), 50)}, 0px 1px 8px ${wrapOpacity(wrapVar(colorSurface200), 50)}`,
    '--box-shadow-03': `0px 2px 8px ${wrapOpacity(wrapVar(colorSurface300), 50)}, 0px 4px 16px ${wrapOpacity(wrapVar(colorSurface200), 50)}`,
    '--box-shadow-04': `0px 3px 12px ${wrapOpacity(wrapVar(colorSurface500), 50)}, 0px 6px 24px ${wrapOpacity(wrapVar(colorSurface300), 50)}`,
    '--box-shadow-05': `0px -4px 4px ${wrapOpacity(wrapVar(colorSurface200), 50)}`,
    '--button-border-radius': '8px',
    '--checkbox-border-radius': '4px',
    '--color-background-critical-dark': wrapVar(colorCritical500),
    '--color-background-critical-light': wrapVar(colorCritical50),
    '--color-background-disabled': wrapVar(colorSurface200),
    '--color-background-hover': wrapVar(colorSurface900),
    '--color-background-hover-inverse': wrapVar(colorSurface50),
    '--color-background-info-dark': wrapVar(colorInfo600),
    '--color-background-info-light': wrapVar(colorInfo50),
    '--color-background-inverse': wrapVar(colorPrimary900),
    '--color-background-overlay': wrapVar(colorSurface900),
    '--color-background-pressed': wrapVar(colorSurface900),
    '--color-background-pressed-inverse': wrapVar(colorSurface50),
    '--color-background-primary': wrapVar(colorSurface50),
    '--color-background-secondary': wrapVar(colorSecondary50),
    '--color-background-subdued': wrapVar(colorSurface100),
    '--color-background-success-dark': wrapVar(colorSuccess900),
    '--color-background-success-light': wrapVar(colorSuccess50),
    '--color-background-tertiary': wrapVar(colorTertiary50),
    '--color-background-warning-dark': wrapVar(colorWarning500),
    '--color-background-warning-light': wrapVar(colorWarning50),
    '--color-border-black': wrapVar(colorSurface900),
    '--color-border-critical': wrapVar(colorCritical400),
    '--color-border-disabled': wrapVar(colorSurface300),
    '--color-border-hover': wrapVar(colorPrimary700),
    '--color-border-info': wrapVar(colorInfo400),
    '--color-border-inverse': wrapVar(colorSurface50),
    '--color-border-primary': wrapVar(colorSurface300),
    '--color-border-secondary': wrapVar(colorSurface200),
    '--color-border-selected': wrapVar(colorPrimary500),
    '--color-border-success': wrapVar(colorSuccess300),
    '--color-border-tertiary': wrapVar(colorSurface100),
    '--color-border-warning': wrapVar(colorWarning300),
    '--color-focus-inverse': wrapVar(colorSurface50),
    '--color-focus-primary': wrapVar(colorPrimary500),
    '--color-icon-critical': wrapVar(colorCritical400),
    '--color-icon-disabled': wrapVar(colorSurface300),
    '--color-icon-info': wrapVar(colorInfo400),
    '--color-icon-inverse': wrapVar(colorSurface50),
    '--color-icon-primary': wrapVar(colorSurface500),
    '--color-icon-secondary': wrapVar(colorPrimary500),
    '--color-icon-success': wrapVar(colorSuccess700),
    '--color-icon-warning': wrapVar(colorWarning600),
    '--color-link-disabled': wrapVar(colorSurface300),
    '--color-link-hover': wrapVar(colorPrimary700),
    '--color-link-inverse': wrapVar(colorSurface50),
    '--color-link-inverse-disabled': wrapVar(colorSurface300),
    '--color-link-inverse-hover': wrapVar(colorSurface100),
    '--color-link-inverse-pressed': wrapVar(colorSurface200),
    '--color-link-monochrome': wrapVar(colorSurface900),
    '--color-link-pressed': wrapVar(colorPrimary900),
    '--color-link-primary': wrapVar(colorPrimary500),
    '--color-link-secondary': wrapVar(colorSurface500),
    '--color-text-critical': wrapVar(colorCritical500),
    '--color-text-disabled': wrapVar(colorSurface300),
    '--color-text-inactive': wrapVar(colorSurface300),
    '--color-text-info': wrapVar(colorInfo700),
    '--color-text-inverse': wrapVar(colorSurface50),
    '--color-text-primary': wrapVar(colorSurface900),
    '--color-text-secondary': wrapVar(colorSurface500),
    '--color-text-success': wrapVar(colorSuccess900),
    '--color-text-warning': wrapVar(colorWarning800),
    '--container-border-radius': '8px',
    '--font-family-primary': "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    '--font-family-secondary': "'Georgia', serif",
    '--font-size-button-100': '14px',
    '--font-size-button-200': '12px',
    '--font-weight-body-primary': '400',
    '--font-weight-body-secondary': '400',
    '--font-weight-button': '600',
    '--font-weight-caption': '400',
    '--font-weight-h1': '400',
    '--font-weight-h2': '400',
    '--font-weight-h3': '400',
    '--font-weight-h4': '400',
    '--font-weight-h5': '600',
    '--font-weight-h6': '600',
    '--font-weight-label-mini': '400',
    '--font-weight-label-strong': '600',
    '--input-border-radius': '6px',
    '--letter-spacing-body-primary': '0.2px',
    '--letter-spacing-body-secondary': '0.2px',
    '--letter-spacing-button': '1px',
    '--letter-spacing-caption': '0.2px',
    '--letter-spacing-h1': '0.2px',
    '--letter-spacing-h1-mobile': '0.2px',
    '--letter-spacing-h2': '0.2px',
    '--letter-spacing-h2-mobile': '0.2px',
    '--letter-spacing-h3': '0.2px',
    '--letter-spacing-h3-mobile': '0.2px',
    '--letter-spacing-h4': '0.2px',
    '--letter-spacing-h5': '0.2px',
    '--letter-spacing-h6': '1px',
    '--letter-spacing-label-mini': '1px',
    '--letter-spacing-label-strong': '0.2px',
    '--search-input-border-radius': '24px',
    '--text-transform-button': 'uppercase',
    '--text-transform-h6': 'uppercase',
    '--text-transform-label-mini': 'uppercase',
    '--width-dense': '1200px',
    '--width-page': '1644px',
} satisfies Record<NonColorCSSVariables, string>;
