// Code generated by copy-phosphor-icons.ts. DO NOT EDIT.
import { IconBase, IconProps } from '../IconBase';
import * as React from 'react';

const weights = {
    bold: React.createElement(
        'svg',
        { fill: 'currentColor', viewBox: '0 0 256 256', xmlns: 'http://www.w3.org/2000/svg' },
        React.createElement('path', {
            d: 'M236,137A108.13,108.13,0,1,1,119,20,12,12,0,0,1,121,44,84.12,84.12,0,1,0,212,135,12,12,0,1,1,236,137ZM116,76v52a12,12,0,0,0,12,12h52a12,12,0,0,0,0-24H140V76a12,12,0,0,0-24,0Zm92,20a16,16,0,1,0-16-16A16,16,0,0,0,208,96ZM176,64a16,16,0,1,0-16-16A16,16,0,0,0,176,64Z',
        })
    ),
    duotone: React.createElement(
        'svg',
        { fill: 'currentColor', viewBox: '0 0 256 256', xmlns: 'http://www.w3.org/2000/svg' },
        React.createElement('path', { d: 'M224,128a96,96,0,1,1-96-96A96,96,0,0,1,224,128Z', opacity: '0.2' }),
        React.createElement('path', {
            d: 'M232,136.66A104.12,104.12,0,1,1,119.34,24,8,8,0,0,1,120.66,40,88.12,88.12,0,1,0,216,135.34,8,8,0,0,1,232,136.66ZM120,72v56a8,8,0,0,0,8,8h56a8,8,0,0,0,0-16H136V72a8,8,0,0,0-16,0Zm40-24a12,12,0,1,0-12-12A12,12,0,0,0,160,48Zm36,24a12,12,0,1,0-12-12A12,12,0,0,0,196,72Zm24,36a12,12,0,1,0-12-12A12,12,0,0,0,220,108Z',
        })
    ),
    fill: React.createElement(
        'svg',
        { fill: 'currentColor', viewBox: '0 0 256 256', xmlns: 'http://www.w3.org/2000/svg' },
        React.createElement('path', {
            d: 'M208,96a12,12,0,1,1,12,12A12,12,0,0,1,208,96ZM196,72a12,12,0,1,0-12-12A12,12,0,0,0,196,72Zm28.66,56a8,8,0,0,0-8.63,7.31A88.12,88.12,0,1,1,120.66,40,8,8,0,0,0,119.34,24,104.12,104.12,0,1,0,232,136.66,8,8,0,0,0,224.66,128ZM128,56a72,72,0,1,1-72,72A72.08,72.08,0,0,1,128,56Zm-8,72a8,8,0,0,0,8,8h48a8,8,0,0,0,0-16H136V80a8,8,0,0,0-16,0Zm40-80a12,12,0,1,0-12-12A12,12,0,0,0,160,48Z',
        })
    ),
    regular: React.createElement(
        'svg',
        { fill: 'currentColor', viewBox: '0 0 256 256', xmlns: 'http://www.w3.org/2000/svg' },
        React.createElement('path', {
            d: 'M232,136.66A104.12,104.12,0,1,1,119.34,24,8,8,0,0,1,120.66,40,88.12,88.12,0,1,0,216,135.34,8,8,0,0,1,232,136.66ZM120,72v56a8,8,0,0,0,8,8h56a8,8,0,0,0,0-16H136V72a8,8,0,0,0-16,0Zm40-24a12,12,0,1,0-12-12A12,12,0,0,0,160,48Zm36,24a12,12,0,1,0-12-12A12,12,0,0,0,196,72Zm24,36a12,12,0,1,0-12-12A12,12,0,0,0,220,108Z',
        })
    ),
};

export const ClockCountdown = React.forwardRef<SVGSVGElement, IconProps>((props, ref) => {
    return (
        <IconBase
            displayName="ClockCountdown"
            ref={ref}
            {...props}
            weights={weights}
        />
    );
});

ClockCountdown.displayName = 'ClockCountdown';
