// Code generated by copy-phosphor-icons.ts. DO NOT EDIT.
import { IconBase, IconProps } from '../IconBase';
import * as React from 'react';

const weights = {
    bold: React.createElement(
        'svg',
        { fill: 'currentColor', viewBox: '0 0 256 256', xmlns: 'http://www.w3.org/2000/svg' },
        React.createElement('path', {
            d: 'M232.49,215.51,185,168a92.12,92.12,0,1,0-17,17l47.53,47.54a12,12,0,0,0,17-17ZM44,112a68,68,0,1,1,68,68A68.07,68.07,0,0,1,44,112Z',
        })
    ),
    duotone: React.createElement(
        'svg',
        { fill: 'currentColor', viewBox: '0 0 256 256', xmlns: 'http://www.w3.org/2000/svg' },
        React.createElement('path', { d: 'M192,112a80,80,0,1,1-80-80A80,80,0,0,1,192,112Z', opacity: '0.2' }),
        React.createElement('path', {
            d: 'M229.66,218.34,179.6,168.28a88.21,88.21,0,1,0-11.32,11.31l50.06,50.07a8,8,0,0,0,11.32-11.32ZM40,112a72,72,0,1,1,72,72A72.08,72.08,0,0,1,40,112Z',
        })
    ),
    fill: React.createElement(
        'svg',
        { fill: 'currentColor', viewBox: '0 0 256 256', xmlns: 'http://www.w3.org/2000/svg' },
        React.createElement('path', {
            d: 'M168,112a56,56,0,1,1-56-56A56,56,0,0,1,168,112Zm61.66,117.66a8,8,0,0,1-11.32,0l-50.06-50.07a88,88,0,1,1,11.32-11.31l50.06,50.06A8,8,0,0,1,229.66,229.66ZM112,184a72,72,0,1,0-72-72A72.08,72.08,0,0,0,112,184Z',
        })
    ),
    regular: React.createElement(
        'svg',
        { fill: 'currentColor', viewBox: '0 0 256 256', xmlns: 'http://www.w3.org/2000/svg' },
        React.createElement('path', {
            d: 'M229.66,218.34l-50.07-50.06a88.11,88.11,0,1,0-11.31,11.31l50.06,50.07a8,8,0,0,0,11.32-11.32ZM40,112a72,72,0,1,1,72,72A72.08,72.08,0,0,1,40,112Z',
        })
    ),
};

export const MagnifyingGlass = React.forwardRef<SVGSVGElement, IconProps>((props, ref) => {
    return (
        <IconBase
            displayName="MagnifyingGlass"
            ref={ref}
            {...props}
            weights={weights}
        />
    );
});

MagnifyingGlass.displayName = 'MagnifyingGlass';
