// Code generated by copy-phosphor-icons.ts. DO NOT EDIT.
import { IconBase, IconProps } from '../IconBase';
import * as React from 'react';

const weights = {
    bold: React.createElement(
        'svg',
        { fill: 'currentColor', viewBox: '0 0 256 256', xmlns: 'http://www.w3.org/2000/svg' },
        React.createElement('path', { d: 'M228,128a12,12,0,0,1-12,12H40a12,12,0,0,1,0-24H216A12,12,0,0,1,228,128Z' })
    ),
    duotone: React.createElement(
        'svg',
        { fill: 'currentColor', viewBox: '0 0 256 256', xmlns: 'http://www.w3.org/2000/svg' },
        React.createElement('path', {
            d: 'M216,56V200a16,16,0,0,1-16,16H56a16,16,0,0,1-16-16V56A16,16,0,0,1,56,40H200A16,16,0,0,1,216,56Z',
            opacity: '0.2',
        }),
        React.createElement('path', { d: 'M224,128a8,8,0,0,1-8,8H40a8,8,0,0,1,0-16H216A8,8,0,0,1,224,128Z' })
    ),
    fill: React.createElement(
        'svg',
        { fill: 'currentColor', viewBox: '0 0 256 256', xmlns: 'http://www.w3.org/2000/svg' },
        React.createElement('path', {
            d: 'M208,32H48A16,16,0,0,0,32,48V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V48A16,16,0,0,0,208,32ZM184,136H72a8,8,0,0,1,0-16H184a8,8,0,0,1,0,16Z',
        })
    ),
    regular: React.createElement(
        'svg',
        { fill: 'currentColor', viewBox: '0 0 256 256', xmlns: 'http://www.w3.org/2000/svg' },
        React.createElement('path', { d: 'M224,128a8,8,0,0,1-8,8H40a8,8,0,0,1,0-16H216A8,8,0,0,1,224,128Z' })
    ),
};

export const Minus = React.forwardRef<SVGSVGElement, IconProps>((props, ref) => {
    return (
        <IconBase
            displayName="Minus"
            ref={ref}
            {...props}
            weights={weights}
        />
    );
});

Minus.displayName = 'Minus';
